# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zBl6JNbWEN7mUUEycQGpLnCShcNxpKp4
"""

mylist = [10,20,30,40,50,60,5]
max = mylist[0]
smax = 0

for i in range(0,len(mylist) ):
  if(mylist[i]>max):
    smax = max
    max=mylist[i]
  elif(mylist[i]>smax):
    smax = mylist[i]
print("sec ",smax)

mylist = [10,20,30,40,50,60,5,60]
max = mylist[0]
smax = 0

for i in range(0,len(mylist) ):
  if(mylist[i]>max):
    smax = max
    max=mylist[i]
  elif(mylist[i]>smax and mylist[i]!=max):
    smax = mylist[i]
print("sec ",smax)

mylist=[10,20,30,4,3,30]
newlist=[]
for i in range(0, len(mylist)):
  if(mylist[i] not in newlist):
    newlist.append(mylist[i])
  else:
    print("duplicate = ",mylist[i])
print(newlist)

mylist=[10,20,30,40]
for i in range(0,1):
  print(mylist[i])
  for j in range(1,4):
    print(mylist[i], mylist[j])

mylist=[10,20,30,40,20,40]
for i in range(0,len(mylist)):
  for j in range(i+1,len(mylist)):
    if(mylist[i] == mylist[j]):
      print("duplicate ",mylist[j])

mylist = [1,2,3,7,14]
target = 9
for i in range(0,len(mylist)):
  for j in range(i+1,len(mylist)):
    if(mylist[i] + mylist[j] == target):
      print("sum ",mylist[i],mylist[j])

a = "hey user"

for i in range(0,len(a)):
  for j in range(i+1,len(a)):
    if(a[i] == a[j]):
      print("duplicate ",a[j])