# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R8wn0Lkgzaig_SmkZWNJH6Uc48BFQ-K6
"""

# list datatype
# list  => datatype,  multiple element can be store together
salary=2000
salary2=3000

# list
# sequence datatype
# int, float, string, tuple ....
# ordered format

x=[10,20,40.5, "hey"]
print(type(x))

x=[10,20,40.5, "hey"]
print( x[-1] )

x=[10,20,40.5, "hey"]
x[0]=99
print(x)

x=[10,20,40.5, "hey"]
x.append(80)
print(x)

# multiple element => extend function

x = [19,25,8,8.4,"hey"]
x.extend("hello")
print(x)

x = [19,25,8,8.4,"hey"]
x.extend(["hello"])
print(x)

mylist = [10,20,30,"def","abc"]
out = mylist.pop()
print(mylist)

print(out)

mylist = [10,20,30,"def","abc"]
mylist.insert(0,"shahid")
print(mylist)

mylist = [10,30,4,76,45,8,2]
mylist.sort()
print(mylist)

mylist = [10,30,76,]
for i in mylist:
  print(i)

mylist = [10,30,76,]
for i in range(0,3):
  print(i,mylist[i])

mylist = [10,30,76,]
for i in range(0,3):
  print(mylist[i])

mylist = [10,30,76]
len(mylist)

mylist = [10,3,20,42,32,888]
max = 0
for i in range(0,len(mylist) ):
  if(mylist[i]>max):
    max=mylist[i]
print(max)

mylist = [10,3,20,42,32,888]
t = sum(mylist)
a = t/len(mylist)

print("total",t)
print("total",a)

help( list )