# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zBl6JNbWEN7mUUEycQGpLnCShcNxpKp4
"""

# valid parenthesis

data = "()"
a = 0
for char in data:
  if(char == "("):
    a = char
  else:
    print("ramain value ",char)

print("a=>",a)

data = "()"
a = 0
for char in data:
  if(char == "("):
    a = char
  elif(char == ")" and "(" == a):
    print("valid ")
  else:
    print("invalid ")

print("a=>",a)

data = "[)"
a = 0
for char in data:
  if(char == "(" or char == "["):
    a = char
  elif((char == ")" and "(" == a) or (char == "]" and "[" == a)):
    print("valid")
  else:
    print("invalid ")

print("a=>",a)

data = "([])"
a = []
for char in data:
  if(char == "(" or char == "[" or char == "{"):
    a.append(char)
  elif((char == ")" and "(" == a.pop()) or (char == "]" and "[" == a.pop())):
    print("valid")
  else:
    print("invalid ")

print("a=>",a)

data = "[]"
a = []
b = 0
for char in data:
  if(char == "(" or char == "[" or char == "{"):
    a.append(char)
  elif((char == ")" and "(" == a.pop()) or (char == "]" and "[" == a.pop())):
    continue
  else:
    b = 1
    break

if(b == 1 or len(a)>1):
  print("invalid")
else:
  print("valid")

data = ")"
a = []
b = 0
for char in data:
  if(char == "(" or char == "[" or char == "{"):
    a.append(char)
  elif(a):
    if((char == ")" and "(" == a.pop()) or (char == "]" and "[" == a.pop())):
      continue
    else:
      b = 1
      break
  else:
    b = 1
    break

if(b == 1 or len(a)>1):
  print("invalid")
else:
  print("valid")

