# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zBl6JNbWEN7mUUEycQGpLnCShcNxpKp4
"""

mylist = [1,2,3,5,7,11,18]
i = 0
end = len(mylist)-1
while(i<len(mylist)):
  print(i, end, mylist[i], mylist[end])
  i+=1
  end-=1

mylist = [1,2,3,5,7,11,18]
i = 0
end = len(mylist)-1
while(i<len(mylist)):
  if(mylist[i]+mylist[end]>9):
    end-=1
  elif(mylist[i]+mylist[end]<9):
    i+=1
  else:
    print("total of two" ,mylist[i], mylist[end])
  i+=1
  end-=1

data = 'saras'
i = 0
out = len(data)-1
end = 0
while(i <= 4):
  if(data[i] != data[out] ):
    end = 2
    break

  i+=1
  out-=1

if(end == 0):
  print("palindrome")
else:
  print("not palidrome")

mylist=[10,10,10,10,31]
newlist=[]
for i in range(0, len(mylist)):
  if(mylist[i] not in newlist):
    newlist.append(mylist[i])
  else:
    print("duplicate = ",mylist[i])
print(newlist)

mylist = [10,20,10,10,10,10,31,40,31]
newlist=[]
for i in range(0, len(mylist)):
  if(mylist[i] not in newlist):
    newlist.append(mylist[i])
  else:
    print("duplicate = ",mylist[i])
print(newlist)

mylist=[10,10,10,10,31]
i=0
newlist=[]
while(i<len(mylist)):
  if(mylist[i] not in newlist):
    newlist.append(mylist[i])
  else:
    print("duplicate = ",mylist[i])
  i+=1
print(newlist)